update trim.sh script to check packages
infinispan/infinispan-images pull request #206
Opened 2023-05-03 06:09 UTC by pminz

2023-05-03 08:27 UTC, ryanemerson requested changes

2023-05-03 08:27 UTC, ryanemerson commented on modules/org/infinispan/dependencies/jdk/openjdk/trim.sh
> +    if [[ $rc -eq 0 ]]
There's no need for the `cmd` and `rc` values here, as bash allows a command to be executed directly in the if statement. For example:

```
if rpm --verify $pkg 2> /dev/null; then
  ...
fi
```

2023-05-03 08:27 UTC, ryanemerson commented on modules/org/infinispan/dependencies/jdk/openjdk/trim.sh
> +        echo "${pkg} does not exist"
The `rpm --verify` command already prints the following out to stdout "package %s is not installed", and stdout is not captured by `2> dev/null`. Therefore, we can just remove this else statement and the output will be the following if we have two packages, one which exists and one which does not:

```
%s exists
package %s is not installed
```

2023-05-03 08:27 UTC, ryanemerson commented on modules/org/infinispan/dependencies/jdk/openjdk/trim.sh
> +#set -e
We shouldn't uncomment this, as we should handle all error scenarios in the script. If this is removed, then it's a sign the script isn't working as we expect.

2023-05-04 12:37 UTC, pminz commented
@ryanemerson I have made the required changes .

2023-05-04 14:19 UTC, merged

2023-05-04 14:19 UTC, ryanemerson commented
Thanks @pminz